### ISSUE TITLE
test fails on Unpickle

### ISSUE THREAD

**Issue by christiananthon** [michael-weinstein/dsNickFury3PlusOrchid#4]
This test works:
python dsNickFury3.3.py -m search -s CCTCTTTGACATCGTGTCCC_GGG -g HG38 --noElevation

But the following fails

python dsNickFury3.3.py -m search -s TGGGGTGATTATGAGCACCG_AGG -g HG38 -p NGG --endClip 3

Traceback (most recent call last):
  File "predictionWrapper.py", line 288, in <module>
    main()
  File "predictionWrapper.py", line 275, in main
    aggregation = Aggregation()
  File "predictionWrapper.py", line 170, in __init__
    self.model, theOtherThing = pickle.load(aggregationModelFile)
  File "/home/local/opt/anaconda2/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/home/local/opt/anaconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
KeyError: 'v'

Traceback (most recent call last):
  File "/home/local/src/elevation/dsNickFury/dsNickFury3PlusOrchid/predictionCaller.py", line 49, in run
    start = predictionOutput.index("<BEGIN_RESULTS>") + 15
ValueError: substring not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dsNickFury3.3.py", line 3760, in <module>
    main()
  File "dsNickFury3.3.py", line 3750, in main
    run = SearchSupervisor()
  File "dsNickFury3.3.py", line 1876, in __init__
    self.aggregateOffTargetScore = self.calculateAggregatedScore()
  File "dsNickFury3.3.py", line 2131, in calculateAggregatedScore
    result = predictionCaller.run("aggregation", stackerScoreList, elevationScoreList, genicScoreList)
  File "/home/local/src/elevation/dsNickFury/dsNickFury3PlusOrchid/predictionCaller.py", line 53, in run
    raise PredictionError("Unable to find data outputs from predictionWrapper.  Output: " %(predictionOutput))
TypeError: not all arguments converted during string formatting

**Comment by christiananthon** [comment]
Turns out to be a problem with git-lfs being over quota for the elevation github project:
[anthon:anthon:0027 @rnai01 Elevation]$ git lfs fetch
fetch: Fetching reference refs/heads/master
batch response: This repository is over its data quota. Purchase more data packs to restore access.                                                                                                        
error: failed to fetch some objects from 'https://github.com/Microsoft/Elevation.git/info/lfs'

Can you fix or provide an alternative download?

**Comment by theDRisin** [comment]
I'm currently having the same exact problem.  Is there a fix?
