### ISSUE TITLE
Debugging dsNickFury fails on test 2

### ISSUE THREAD

**Issue by theDRisin** [michael-weinstein/dsNickFury3PlusOrchid#7]
The following:
'python dsNickFury3.3.py -m search -s CCTCTTTGACATCGTGTCCC_GGG -g HG38 --noElevation'

Works just fine, but the second test

'python dsNickFury3.3.py -m search -s TGGGGTGATTATGAGCACCG_AGG -g HG38 -p NGG --endClip 3'

Gives the following error:

Traceback (most recent call last):
  File "predictionWrapper.py", line 288, in <module>
    main()
  File "predictionWrapper.py", line 275, in main
    aggregation = Aggregation()
  File "predictionWrapper.py", line 170, in __init__
    self.model, theOtherThing = pickle.load(aggregationModelFile)
  File "/Users/dave/dsnickfury/dependencies/anaconda2/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/Users/dave/dsnickfury/dependencies/anaconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
KeyError: 'v'

Traceback (most recent call last):
  File "/Users/dave/dsnickfury/dsNickFury3PlusOrchid/predictionCaller.py", line 49, in run
    start = predictionOutput.index("<BEGIN_RESULTS>") + 15
ValueError: substring not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dsNickFury3.3.py", line 3760, in <module>
    main()
  File "dsNickFury3.3.py", line 3750, in main
    run = SearchSupervisor()
  File "dsNickFury3.3.py", line 1876, in __init__
    self.aggregateOffTargetScore = self.calculateAggregatedScore()
  File "dsNickFury3.3.py", line 2131, in calculateAggregatedScore
    result = predictionCaller.run("aggregation", stackerScoreList, elevationScoreList, genicScoreList)
  File "/Users/dave/dsnickfury/dsNickFury3PlusOrchid/predictionCaller.py", line 53, in run
    raise PredictionError("Unable to find data outputs from predictionWrapper.  Output: " %(predictionOutput))
TypeError: not all arguments converted during string formatting

Any suggestions on a fix?

**Comment by JoshTycko** [comment]
For me, the first test works but the second test fails at a similar point. I would really appreciate any suggestions you may have. Thanks.


____________________________________________________________________________________________
`/mnt/lab_data/bassik/jtycko/dsNickFury3PlusOrchid/dependencies/anaconda2/envs/dsNickFury/bin/python dsNickFury3.3.py -s TGGGGTGATTATGAGCACCG_AGG -g HG38 -p NGG --endClip 3 -m search`
Version 3.2 (The Orchid edition. Perfecting the replacement base fragment. I totally asked for this.)
By Michael M. Weinstein, Copyright 2016
Dan Cohn Laboratory and Collaboratory, University of California, Los Angeles
Creating job list

Using a cache size of 25000000
Loading binary site data.
Analyzing final set of sites
Found 993 matching sites.
Calculating Azimuth Score
Sorting
Annotating
Calculating Elevation Scores
Submitting 952 sites. 41 redundant sites deduplicated.
Traceback (most recent call last):
  File "predictionWrapper.py", line 288, in <module>
    main()
  File "predictionWrapper.py", line 270, in main
    elevation = Elevation()
  File "predictionWrapper.py", line 65, in __init__
    from elevation.cmds import predict as elevation
  File "/mnt/lab_data/bassik/jtycko/dsNickFury3PlusOrchid/dependencies/elevation/elevation/cmds/predict.py", line 13, in <module>
    import elevation.prediction_pipeline as pp
  File "/mnt/lab_data/bassik/jtycko/dsNickFury3PlusOrchid/dependencies/elevation/elevation/prediction_pipeline.py", line 4, in <module>
    import joblib
ImportError: No module named joblib

Traceback (most recent call last):
  File "/mnt/lab_data/bassik/jtycko/dsNickFury3PlusOrchid/dsNickFury3PlusOrchid/predictionCaller.py", line 49, in run
    start = predictionOutput.index("<BEGIN_RESULTS>") + 15
ValueError: substring not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dsNickFury3.3.py", line 3760, in <module>
    main()
  File "dsNickFury3.3.py", line 3750, in main
    run = SearchSupervisor()
  File "dsNickFury3.3.py", line 1875, in __init__
    self.applyElevationScores(args.sequence)
  File "dsNickFury3.3.py", line 2096, in applyElevationScores
    elevationScoreList = calculateElevationScoreLocal(intendedTarget.replace("_",""), offTargetSequences)
  File "dsNickFury3.3.py", line 1726, in calculateElevationScoreLocal
    results = predictionCaller.run("elevation", intendedTarget, offTargetList)
  File "/mnt/lab_data/bassik/jtycko/dsNickFury3PlusOrchid/dsNickFury3PlusOrchid/predictionCaller.py", line 53, in run
    raise PredictionError("Unable to find data outputs from predictionWrapper.  Output: " %(predictionOutput))
TypeError: not all arguments converted during string formatting`

**Comment by michael-weinstein** [comment]
I think there is an issue where some of the data being stored on github is not being transferred properly.  I am still looking into a way to fix this.  @jjc2718 I think we discussed this before.

**Comment by lfearnley** [comment]
@JoshTycko: 
I'm assuming you've checked that joblib is installed in the elevation environment? 

The error messages you're generating are:

1) Elevation can't import joblib; it fails to run - "ImportError: No module named joblib" in 'dependencies/elevation/elevation/prediction_pipeline.py'
2) dsNickFury attempts to parse the output from elevation; unable to find it, it throws an exception - "ValueError: substring not found" for "<BEGIN RESULTS>"
3) dsNickFury tries to raise an exception, but it can't convert predictionOutput to a string for some reason, so it throws another exception - "TypeError: not all arguments converted during string formatting"

**Comment by JoshTycko** [comment]
Yes, joblib is installed in the elevation environment via `pip`. It works if I `source activate elevation`, open a python interpreter, and `import joblib`.

I haven't yet found a way to resolve error 1. Please let me know if you think of anything or think I should focus on the other errors. 

@michael-weinstein I did find that individually downloading the pickle files from Github was able to fix errors earlier in the installation (as mentioned in another Issue board). Please let me know if there is a certain datafile I should download. 

I have noticed that I'm missing a few files: `test_aggregation.txt` and `test_elevation.txt` for debugging the model and the translation.pkl file for the third test of dsNickFury

**Comment by lfearnley** [comment]
I'm happy to defer to @michael-weinstein on this one, it's his code after all, but I'm 99% certain that the other error messages are all there because there's no output from Elevation.

What's the output of ./pip freeze run from <your path here>/CRISPR/dsnickfury/dependencies/anaconda2/envs/elevation/bin ?

**Comment by JoshTycko** [comment]
Thank you for this helpful comment! In checking the pip freeze outputs I noticed that joblib was missing from this anaconda2 location (a different location than the one you posted above):
`dsNickFury3PlusOrchid/dependencies/anaconda2/bin/pip freeze`

So I installed it:
`dsNickFury3PlusOrchid/dependencies/anaconda2/bin/pip install joblib`

Then I was able to successfully run the 2nd test and get this aggregate score:
`Aggregate mismatch risk: 0.40794333578434433`
This matches the score available online at crispr.ml.

Thanks again!
